"""add indexes to problems

Revision ID: 26015dd9a702
Revises: a1b2c3d4e5f6
Create Date: 2026-06-15 14:18:36.701024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26015dd9a702'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_problems_category_id', 'problems', ['category_id'], unique=False)
    op.create_index('ix_problems_created_at', 'problems', ['created_at'], unique=False)
    op.create_index('ix_problems_created_by', 'problems', ['created_by'], unique=False)
    op.create_index('ix_problems_status', 'problems', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_problems_status', table_name='problems')
    op.drop_index('ix_problems_created_by', table_name='problems')
    op.drop_index('ix_problems_created_at', table_name='problems')
    op.drop_index('ix_problems_category_id', table_name='problems')
    # ### end Alembic commands ###
