"""add address to problems

Revision ID: 9957fcf2c2d0
Revises: 44488d9f7777
Create Date: 2026-06-15 13:20:09.013870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9957fcf2c2d0'
down_revision: Union[str, Sequence[str], None] = '44488d9f7777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'address')
    # ### end Alembic commands ###
